### ISSUE TITLE
Uncaught ReferenceError: exports is not defined at index.js:2:23

### ISSUE THREAD

**Issue by jemraider21** [jemraider21/CMSC_405_Project_4#1]
When I run `npm start` to run the program, the alert message does not run, indicating that the `index.js` script is not running correctly. Opening up the dev tools console reveals the following error:  
```javascript
Uncaught ReferenceError: exports is not defined at index.js:2:23
```

**Comment by jemraider21** [comment]
A workaround to removing the `export is not defined` issue is by adding a script tag in the index.html file before any other script tag that says the following: 
```html
<script>var exports = {};</script>
```

This then spawns a new issue where `require` is not defined. A solution is to add a script tag that references require.js:
```html
<script data-main="./js/frontend/index.js" src="https://requirejs.org/docs/release/2.3.5/minified/require.js"></script>
```

After adding the script tag, a new issue comes forth:
```javascript
require.js:5 Uncaught Error: Module name "models/shapes/ShapePositions" has not been loaded yet for context: _. Use require([])
http://requirejs.org/docs/errors.html#notloaded
    at makeError (require.js:5:1067)
    at Object.o [as require] (require.js:5:11053)
    at requirejs (require.js:5:14737)
    at VM60 index.js:3:26
```

**Comment by jemraider21** [comment]
What is happening is that the server is having a difficult time with finding the additional javascript files that index.js calls on. It's weird since the directories those files are in are children directories of `src/main/frontend/js` and it's able to find index.js just fine.

What I might have to do is restructure the program so that the compiled javascript appears in the same directory of the typescript file. What this would look like (file structure wise) is this:

- src/main
- - frontend
- - backend
